services:
  - type: web
    name: your-portfolio
    runtime: java
    buildCommand: |
      chmod +x mvnw
      ./mvnw clean package
    startCommand: java -jar target/portfolio-*.jar
    env:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod